using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using QuanLyCongViec.Models;
using System.Globalization;
using DevExpress.XtraGrid.Views.Grid;
using DevExpress.Utils;

namespace QuanLyCongViec.Views.Forms.Leader
{
    public partial class QuanLyNhanVien : DevExpress.XtraEditors.XtraUserControl
    {
        
        private static QuanLyNhanVien _instance;
        public static QuanLyNhanVien Instance
        {
            get
            {
                if (_instance == null)

                    _instance = new QuanLyNhanVien();
                return _instance;

            }
        }
        public QuanLyNhanVien()
        {
            InitializeComponent();
            ModelsDataContext modelsDataContext = new ModelsDataContext();
            gridControl1.DataSource = modelsDataContext.sp_getListMember();
            // This line of code is generated by Data Source Configuration Wizard
            gridControl1.DataSource = modelsDataContext.sp_getListMember();
            gridView1.Columns["MaNhanVien"].View.OptionsBehavior.EditorShowMode = EditorShowMode.MouseUp;
            gridView1.RowClick += gridView1_RowClick;
        }

        private void btnThem_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            if (textBoxEmail.Text.Length > 3 && textBoxMK.Text.Length > 3 && textBoxNhapLaiMK.Text.Length > 3
                                                  && textBoxMaNV.Text.Length > 3
                                                  && textBoxTenNV.Text.Length > 3 && textBoxDiaChi.Text.Length > 3)
            {
                MessageBox.Show("Xin Nhập Đủ Dữ Liệu");
            }
            else
            {
                dateTimePickerNgaySinh.Value = DateTime.ParseExact("1/1/1999", "dd/MM/yyyy", CultureInfo.InvariantCulture);
                ModelsDataContext modelsDataContext = new ModelsDataContext();
                if (textBoxMK.Text.Trim().Equals(textBoxNhapLaiMK.Text.Trim()))
                {
                    if (radioButtonNam.Checked == true)
                    {
                        modelsDataContext.sp_addMember(textBoxEmail.Text, textBoxMK.Text, textBoxMaNV.Text, textBoxTenNV.Text,
                                                        textBoxDiaChi.Text, true, dateTimePickerNgaySinh.Value);
                    }
                    else if (radioButtonNu.Checked == true)
                    {
                        modelsDataContext.sp_addMember(textBoxEmail.Text, textBoxMK.Text, textBoxMaNV.Text, textBoxTenNV.Text,
                                                                          textBoxDiaChi.Text, false, dateTimePickerNgaySinh.Value);
                    }
                    XtraMessageBox.Show("Thêm Quản Lý Thành Công");
                    taiLai();
                }

            }

        }
        private void taiLai()
        {
            ModelsDataContext modelsDataContext = new ModelsDataContext();
            gridControl1.DataSource = modelsDataContext.sp_getListMember();
            gridControl1.Refresh();
        }

        private void btnTaiLai_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {

            ModelsDataContext modelsDataContext = new ModelsDataContext();
            gridControl1.DataSource = modelsDataContext.sp_getListMember();
            gridControl1.Refresh();

        }

      

        private void btnXoa_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            gridView1.DeleteRow(gridView1.FocusedRowHandle);
            ModelsDataContext modelsDataContext = new ModelsDataContext();
            modelsDataContext.sp_deleteMember(textBoxMaNV.Text);
            XtraMessageBox.Show("Xóa Thành Công!" + textBoxMaNV.Text);
            taiLai();

        }

        private void btnLamMoi_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            textBoxMaNV.Text = "";
            textBoxTenNV.Text = "";
            textBoxEmail.Text = "";
            textBoxDiaChi.Text = "";
            textBoxMK.Text = "";
            textBoxNhapLaiMK.Text = "";
            radioButtonNam.Checked = false;
            radioButtonNu.Checked = false;
            dateTimePickerNgaySinh.Value = DateTime.Now;
        }

        private void btnSua_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            ModelsDataContext modelsDataContext = new ModelsDataContext();

            if (textBoxEmail.Text.Length < 3 && textBoxMaNV.Text.Length < 3 && textBoxTenNV.Text.Length < 3 && textBoxDiaChi.Text.Length < 3)
            {
                MessageBox.Show("Xin Nhập Đủ Dữ Liệu");
            }
            else
            {
                //dateTimePickerNgaySinh.Value = DateTime.ParseExact("1/1/1999", "dd/MM/yyyy", CultureInfo.InvariantCulture);

                if (textBoxMK.Text.Trim().Equals(textBoxNhapLaiMK.Text.Trim()))
                {
                    if (radioButtonNam.Checked == true)
                    {
                        modelsDataContext.sp_editMember(textBoxMaNV.Text,
                            textBoxTenNV.Text,
                            textBoxDiaChi.Text,
                            true,
                            dateTimePickerNgaySinh.Value,
                            textBoxEmail.Text,
                            textBoxMK.Text);
                    }
                    else if (radioButtonNu.Checked == true)
                    {
                        modelsDataContext.sp_editMember(
                            textBoxMaNV.Text,
                            textBoxTenNV.Text,
                            textBoxDiaChi.Text,
                            false,
                            dateTimePickerNgaySinh.Value,
                            textBoxEmail.Text,
                            textBoxMK.Text);

                    }
                    XtraMessageBox.Show("Cập Nhật Quản Lý Thành Công");
                    taiLai();
                }

            }
        }

        
            private void gridView1_RowClick(object sender, DevExpress.XtraGrid.Views.Grid.RowClickEventArgs e)
            {
                textBoxMaNV.EditValue = (sender as GridView).GetFocusedRowCellValue("MaNhanVien");
                textBoxTenNV.EditValue = (sender as GridView).GetFocusedRowCellValue("TenNhanVien");
                textBoxDiaChi.EditValue = (sender as GridView).GetFocusedRowCellValue("DiaChiNhanVien");
                textBoxEmail.EditValue = (sender as GridView).GetFocusedRowCellValue("Email");
                radioButtonNam.Checked = !((sender as GridView).GetFocusedRowCellValue("GioiTinhNhanVien")).Equals(false);
                radioButtonNu.Checked = ((sender as GridView).GetFocusedRowCellValue("GioiTinhNhanVien")).Equals(false);

                //XtraMessageBox.Show((sender as GridView).GetFocusedRowCellValue("NgaySinhNhanVien").ToString());
                string iDate = (sender as GridView).GetFocusedRowCellValue("NgaySinhNhanVien").ToString();
                DateTime oDate = Convert.ToDateTime(iDate);
                dateTimePickerNgaySinh.Value = oDate;
            }
        
    }
}
